services:
  postgres:
    image: postgres:16-alpine
    container_name: library-db
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U library_user -d library_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: library-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: library_db
      DB_USERNAME: library_user
      DB_PASSWORD: library_pass
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
