openapi: 3.0.3
info:
  title: es-library-api
  version: 1.0.0
  description: Library service API

paths:
  # Books
  /v1/library/books:
    $ref: './library/books-v1.api.yaml'
  /v1/library/books/{id}:
    $ref: './library/books-id-v1.api.yaml'
  # Users
  /v1/library/users:
    $ref: './library/users-v1.api.yaml'
  /v1/library/users/{id}:
    $ref: './library/users-id-v1.api.yaml'
  # Loans
  /v1/library/loans:
    $ref: './library/loans-v1.api.yaml'
  /v1/library/loans/{id}:
    $ref: './library/loans-id-v1.api.yaml'
  /v1/library/loans/{id}/return:
    $ref: './library/loans-id-return-v1.api.yaml'
  # Fines
  /v1/library/fines/{id}:
    $ref: './library/fines-id-v1.api.yaml'

components:
  schemas:
    ApiError:
      $ref: './components/ApiErrorV1.yaml'
    BookV1:
      $ref: './components/BookV1.yaml'
    PostBookV1Request:
      $ref: './requests/PostBookV1Request.yaml'
    PatchBookV1Request:
      $ref: './requests/PatchBookV1Request.yaml'
    UserV1:
      $ref: './components/UserV1.yaml'
    PostUserV1Request:
      $ref: './requests/PostUserV1Request.yaml'
    LoanV1:
      $ref: './components/LoanV1.yaml'
    PostLoanV1Request:
      $ref: './requests/PostLoanV1Request.yaml'
    PatchLoanReturnV1Request:
      $ref: './requests/PatchLoanReturnV1Request.yaml'
    
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
